const GET_LIST_ITEMS = 'GET_LIST_ITEMS';
const POST_LIST_ITEMS = 'POST_LIST_ITEMS';
const DELETE_LIST_ITEMS = 'DELETE_LIST_ITEMS';
const ADD_ITEM = 'ADD_ITEM';

export default {
	GET_LIST_ITEMS,
	POST_LIST_ITEMS,
	DELETE_LIST_ITEMS,
	ADD_ITEM
};
