const GET_LIST_ITEMS = 'GET_LIST_ITEMS';
const POST_LIST_ITEMS = 'POST_LIST_ITEMS';
const DELETE_LIST_ITEMS = 'DELETE_LIST_ITEMS';
const ADD_ITEM = 'ADD_ITEM';
const ADD_ITEM_START = 'ADD_ITEM_START';
const ADD_ITEM_ERROR = 'ADD_ITEM_ERROR';
const GET_LIST_ITEMS_ERROR = 'GET_LIST_ITEMS_ERROR';
const DELETE_LIST_ITEMS_ERROR = 'DELETE_LIST_ITEMS_ERROR';

export default {
	GET_LIST_ITEMS,
	POST_LIST_ITEMS,
	DELETE_LIST_ITEMS,
	ADD_ITEM,
	ADD_ITEM_START,
	ADD_ITEM_ERROR,
	GET_LIST_ITEMS_ERROR,
	DELETE_LIST_ITEMS_ERROR
};
