const GET_LIST_ITEMS = 'GET_LIST_ITEMS';
const POST_LIST_ITEMS = 'POST_LIST_ITEMS';
const DELETE_LIST_ITEMS = 'DELETE_LIST_ITEMS';

export default {
	GET_LIST_ITEMS,
	POST_LIST_ITEMS,
	DELETE_LIST_ITEMS,
};
